### ISSUE TITLE
0/10 would never use again

### ISSUE THREAD

**Issue by leonskij** [Vandesm14/fridgesales.info#1]
If you look at the statistics, this site is off by a bit. Totally unusable. **0/10 would never use again**.

**Comment by Vandesm14** [comment]
Marked as duplicate #1

**Comment by leonskij** [comment]
**-1/10** - ¹²³€½¾{[]}\¸@łe¶ŧ←↓→øþ¨~æßðđŋħˀĸł´^`«»¢“”nµ,· ̣
